"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Loader2 } from "lucide-react"

export function ContactForm() {
  const [selectedPackage, setSelectedPackage] = useState("standard")

    return (
        <form
              action="https://formsubmit.co/ogbetatesters@proton.me"
                    method="POST"
                          className="space-y-4"
                              >
                                    <h3 className="text-xl font-bold text-white">Get Started Today</h3>
                                          <p className="text-sm text-zinc-300">Fill out the form below and we'll get back to you within 24 hours.</p>

                                                <div className="grid gap-4 sm:grid-cols-2">
                                                        <div className="space-y-2">
                                                                  <Label htmlFor="first-name" className="text-white">First name</Label>
                                                                            <Input id="first-name" name="First Name" placeholder="John" required className="bg-black/50 border-white/10 text-white" />
                                                                                    </div>
                                                                                            <div className="space-y-2">
                                                                                                      <Label htmlFor="last-name" className="text-white">Last name</Label>
                                                                                                                <Input id="last-name" name="Last Name" placeholder="Doe" required className="bg-black/50 border-white/10 text-white" />
                                                                                                                        </div>
                                                                                                                              </div>

                                                                                                                                    <div className="space-y-2">
                                                                                                                                            <Label htmlFor="email" className="text-white">Email</Label>
                                                                                                                                                    <Input id="email" name="Email" placeholder="john@example.com" type="email" required className="bg-black/50 border-white/10 text-white" />
                                                                                                                                                          </div>

                                                                                                                                                                <div className="space-y-2">
                                                                                                                                                                        <Label htmlFor="company" className="text-white">Company</Label>
                                                                                                                                                                                <Input id="company" name="Company" placeholder="Your Company" className="bg-black/50 border-white/10 text-white" />
                                                                                                                                                                                      </div>

                                                                                                                                                                                            <div className="space-y-2">
                                                                                                                                                                                                    <Label htmlFor="package" className="text-white">Package</Label>
                                                                                                                                                                                                            <select
                                                                                                                                                                                                                      id="package"
                                                                                                                                                                                                                                name="Package"
                                                                                                                                                                                                                                          value={selectedPackage}
                                                                                                                                                                                                                                                    onChange={(e) => setSelectedPackage(e.target.value)}
                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                        className="w-full rounded-md border border-white/10 bg-black/50 p-2 text-white focus:outline-none focus:ring-2 focus:ring-primary"
                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                          <option value="basic">Basic ($8)</option>
                                                                                                                                                                                                                                                                                                    <option value="standard">Standard ($15)</option>
                                                                                                                                                                                                                                                                                                              <option value="premium">Premium ($20)</option>
                                                                                                                                                                                                                                                                                                                        <option value="enterprise">Enterprise ($50)</option>
                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                            <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                    <Label htmlFor="message" className="text-white">Message</Label>
                                                                                                                                                                                                                                                                                                                                                            <Textarea
                                                                                                                                                                                                                                                                                                                                                                      id="message"
                                                                                                                                                                                                                                                                                                                                                                                name="Message"
                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Tell us about your app and testing requirements..."
                                                                                                                                                                                                                                                                                                                                                                                                    rows={4}
                                                                                                                                                                                                                                                                                                                                                                                                              className="bg-black/50 border-white/10 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Hidden FormSubmit Fields */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="hidden" name="_next" value="https://ogbetatesters.vercel.app/thank-you.html" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="hidden" name="_captcha" value="false" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="hidden" name="_subject" value="New Beta Tester Inquiry" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="text" name="_honey" style={{ display: "none" }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Button type="submit" className="w-full bg-primary hover:bg-primary/90">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Submit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
