"use client"

import React, { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Loader2 } from "lucide-react"

export function ContactForm() {
  const [isSubmitted, setIsSubmitted] = useState(false)
    const [selectedPackage, setSelectedPackage] = useState("standard")

      if (isSubmitted) {
          return (
                <div className="flex flex-col items-center justify-center space-y-4 py-12">
                        <div className="flex h-20 w-20 items-center justify-center rounded-full bg-primary/20">
                                  <svg
                                              xmlns="http://www.w3.org/2000/svg"
                                                          width="24"
                                                                      height="24"
                                                                                  viewBox="0 0 24 24"
                                                                                              fill="none"
                                                                                                          stroke="currentColor"
                                                                                                                      strokeWidth="2"
                                                                                                                                  strokeLinecap="round"
                                                                                                                                              strokeLinejoin="round"
                                                                                                                                                          className="h-10 w-10 text-primary"
                                                                                                                                                                    >
                                                                                                                                                                                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
                                                                                                                                                                                            <polyline points="22 4 12 14.01 9 11.01" />
                                                                                                                                                                                                      </svg>
                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                      <h3 className="text-2xl font-bold text-white">Thanks for reaching out!</h3>
                                                                                                                                                                                                                              <p className="text-center text-zinc-300">
                                                                                                                                                                                                                                        We've received your message and will get back to you within 24 hours.
                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                        <Button
                                                                                                                                                                                                                                                                  variant="outline"
                                                                                                                                                                                                                                                                            className="border-primary text-primary hover:bg-primary/10"
                                                                                                                                                                                                                                                                                      onClick={() => setIsSubmitted(false)}
                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                        Send Another Message
                                                                                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                  <form
                                                                                                                                                                                                                                                                                                                                        action="https://formsubmit.co/ogbetatesters@proton.me"
                                                                                                                                                                                                                                                                                                                                              method="POST"
                                                                                                                                                                                                                                                                                                                                                    className="space-y-4"
                                                                                                                                                                                                                                                                                                                                                          onSubmit={() => setIsSubmitted(true)}
                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-xl font-bold text-white">Get Started Today</h3>
                                                                                                                                                                                                                                                                                                                                                                          <p className="text-sm text-zinc-300">Fill out the form below and we'll get back to you within 24 hours.</p>

                                                                                                                                                                                                                                                                                                                                                                                <div className="grid gap-4 sm:grid-cols-2">
                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                  <Label htmlFor="first-name" className="text-white">First name</Label>
                                                                                                                                                                                                                                                                                                                                                                                                            <Input
                                                                                                                                                                                                                                                                                                                                                                                                                        id="first-name"
                                                                                                                                                                                                                                                                                                                                                                                                                                    name="first_name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="John"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-black/50 border-white/10 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Label htmlFor="last-name" className="text-white">Last name</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id="last-name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name="last_name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Doe"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-black/50 border-white/10 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Label htmlFor="email" className="text-white">Email</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="john@example.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-black/50 border-white/10 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Label htmlFor="company" className="text-white">Company</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id="company"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="company"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Your Company"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-black/50 border-white/10 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Label htmlFor="package" className="text-white">Package</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id="package"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name="package"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={selectedPackage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setSelectedPackage(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-black/50 border-white/10 text-white px-4 py-2 rounded-md w-full appearance-none focus:outline-none focus:ring-2 focus:ring-primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="basic">Basic ($8)</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="standard">Standard ($15)</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="premium">Premium ($20)</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="enterprise">Enterprise ($50)</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Label htmlFor="message" className="text-white">Message</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id="message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name="message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Tell us about your app and testing requirements..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rows={4}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="bg-black/50 border-white/10 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* FormSubmit hidden fields */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input type="hidden" name="_captcha" value="false" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="hidden" name="_subject" value="New Beta Tester Inquiry" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input type="hidden" name="_template" value="table" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="text" name="_honey" style={{ display: "none" }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Button type="submit" className="w-full bg-primary hover:bg-primary/90">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Submit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
